version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - yum update -y
      - yum install -y httpd

  build:
    commands:
      - echo Building the application

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
